### ISSUE TITLE
Background color isn't loading

### ISSUE THREAD

**Issue by beardofedu** [beardofedu-test/calculator#16]
The background color isn't loading on `prod` or `dev`, the current color of `#7acc9z` isn't an actual color and was supposed to be `#7acc9e`.

![image](https://user-images.githubusercontent.com/18329853/115650993-4fd6d300-a2f8-11eb-8856-30b182f45b4b.png)

**Comment by Hollywood** [comment]
I'm on it. Will link appropriate PR.
